### ISSUE TITLE
How to pu a Recaptcha widget between Flutter widgets?

### ISSUE THREAD

**Issue by hsynksahin** [bharathraj-e/g_recaptcha_v3#11]
I've checked almost any other issue here, 
What I've understand is that we need a html file working in a API/Website, and then we need to redirect user to that View by using WebView widget than the google will handle the visual part.

My question is that, what if we want that visual part with in a page,
For example we have a login page, an username input, a password input, and then a submit button.
When user fails to enter password right for at least 2 times I want to check that if user is a human by recaptcha.
A Webview should apper between  the password and submit button (or at the bottom)  to show user that they have to submit recaptcha.

The problem is if I basicly put a Weview there, I dont know how much height I should give it. And will it expand when the bigger modal shown. Will it be responsive to other screen aspect ratios?

If I use a Stack Widget, that contains all other widgets in a Column, and captcha as other child, I can maybe simulate the height requested by the Recaptcha on the other hand and the modal pop-up will be shown normally.

Anyone tried that ? How to put a recaptcha in between a FlutterUI design? Basicly I dont want to put a HTML page in my app.

**Comment by bharathraj-e** [comment]
+1
