### ISSUE TITLE
Update to pacackge:web

### ISSUE THREAD

**Issue by JgomesAT** [bharathraj-e/g_recaptcha_v3#13]
is there any option to upgrade this package to new package:web of flutter 3.19

**Comment by bharathraj-e** [comment]
is there any issue ?

**Comment by JgomesAT** [comment]
Not really, but is necessary if you want to compile in wasm your project

"To run Flutter applications on the web using WebAssembly, you need to migrate all code — from the application and all dependencies — to use the new JavaScript Interop mechanism and the [package:web](https://pub.dev/packages/web). The legacy JavaScript and browser libraries remain unchanged and supported for compiling to JavaScript code. However, compiling to WebAssembly requires a migration."

**Comment by JgomesAT** [comment]
I think this is done, with version 0.0.6
