### ISSUE TITLE
Support to js: 0.7.1

### ISSUE THREAD

**Issue by JgomesAT** [bharathraj-e/g_recaptcha_v3#14]
To add possibility to compile WASM in the projects its necessary update de js library to 0.7.1

**Comment by JgomesAT** [comment]
is the schedule a migration to WASM?

now I HAve this error:

../../../../.pub-cache/hosted/pub.dev/g_recaptcha_v3-0.0.6/lib/g_recaptcha_v3_web.dart:5:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' as HTML;

g_recaptcha_v3-0.0.6/lib/g_recaptcha_v3_web.dart:11:1: Error: JS interop library 'package:js/js_util.dart' can't be
imported when compiling to Wasm.
Try using 'dart:js_interop' or 'dart:js_interop_unsafe' instead.
import 'package:js/js_util.dart' as js_util;
^

**Comment by bharathraj-e** [comment]
Hi @JgomesAT 

Apologies for the delayed response, and thank you for bringing this up!

I'm happy to inform you that WASM support has now been integrated into the plugin. Please update to version 1.0.0, which includes this support.

I’ll be closing this issue now, but feel free to reopen it or create a new issue if you encounter any problems or have further questions.

Thank you for your patience and for using the plugin!
