### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by simeonangelov94** [bharathraj-e/g_recaptcha_v3#15]
Hello,

When I try to run the recaptcha on a production environment get the following error. I use Firebase Hosting

Error Message
XMLHttpRequest cannot load https://www.google.com/recaptcha/api/siteverify due to access control checks.

Is there a step in the implementation that I am missing. Thank you.

**Comment by bharathraj-e** [comment]
https://github.com/bharathraj-e/g_recaptcha_v3/issues/4
