### ISSUE TITLE
It will be cool if its support wasm as per new flutter stable version 3.22.0

### ISSUE THREAD

**Issue by ps6067966** [bharathraj-e/g_recaptcha_v3#16]

**Comment by marco-dinamo** [comment]
+1

**Comment by DeepakKishore-Instrive** [comment]
+1

**Comment by bharathraj-e** [comment]
Hi @ps6067966 @marco-dinamo @DeepakKishore-Instrive 

Apologies for the delay in addressing this request. I’ve now integrated WASM support for the plugin. Version 1.0.0 with WASM support is live.

I’m closing this issue now, but please feel free to reopen it if you encounter any issues.

Thank you for your patience and suggestion!
