### ISSUE TITLE
set different key on multiple environment

### ISSUE THREAD

**Issue by rymesaint** [bharathraj-e/g_recaptcha_v3#17]
How to set the key on multiple environment?

**Comment by bharathraj-e** [comment]
Hi @rymesaint 

From version **1.0.0**, there is no longer a need to manually add the script to the HTML `<head>` tag. The required script is automatically included during the `GRecaptchaV3.ready(<recaptcha key>)` call.

To handle different environments, simply update the key dynamically in the `ready` method based on your environment. For example:

```dart
void initializeRecaptcha() {
  String recaptchaKey;

  // Example: Switch keys based on environment
  if (isProduction) {
    recaptchaKey = 'YOUR_PRODUCTION_KEY';
  } else {
    recaptchaKey = 'YOUR_DEV_OR_TEST_KEY';
  }

  // Initialize reCAPTCHA with the corresponding key
  GRecaptchaV3.ready(recaptchaKey);
}
```

This approach allows you to set a different key for each environment without modifying the HTML or adding scripts manually.
