### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by ervindobri** [bharathraj-e/g_recaptcha_v3#6]

**Comment by bharathraj-e** [comment]
Google recaptcha V3 is based on pure javascript only.
Ref : [https://developers.google.com/recaptcha/docs/versions#:~:text=It%20is%20a%20pure%20JavaScript%20API%20returning%20a%20score](https://developers.google.com/recaptcha/docs/versions#:~:text=It%20is%20a%20pure%20JavaScript%20API%20returning%20a%20score)

There is no support for android / ios integration is provided for v3.

**Comment by bharathraj-e** [comment]
[Try this for mobile support](https://github.com/bharathraj-e/g_recaptcha_v3/issues/9#issuecomment-1726784944)
