### ISSUE TITLE
Refused to frame 'https://www.google.com/' because it violates the following Content Security Policy directive: "default-src 'self' *.numifinancial.com *.finunity.tech *.comivapay.com *.googleapis.com *.gstatic.com *.fontawesome.com *.google-analytics.com unpkg.com *.mojohelpdesk.com". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

### ISSUE THREAD

**Issue by karan-jarvis** [bharathraj-e/g_recaptcha_v3#7]
![Screenshot 0004-06-22 at 5 20 40 PM](https://user-images.githubusercontent.com/62132474/175022738-df9d651e-d496-4475-b6b3-93de1509da6f.png)

 @bharathraj-e   Google ReCaptcha is not displaying in  live mode also throw the error please check it and give me solution for that overall very good package for google reCaptcha thank you

**Comment by bharathraj-e** [comment]
@karan-jarvis i can see the console log says `gRecaptcha V3 ready`. 
- Have you tried `execute()`? - Does it generates token without error?
- For ReCaptcha banner - Did you tried `showBadge()` .

please share your index.html file.

**Comment by karan-jarvis** [comment]
I got the error sir thank you so very much

> @karan-jarvis i can see the console log says `gRecaptcha V3 ready`.
> 
> * Have you tried `execute()`? - Does it generates token without error?
> * For ReCaptcha banner - Did you tried `showBadge()` .
> 
> please share your index.html file.
